name: Docker Build Action

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout karo
        uses: actions/checkout@v3

      - name: Docker build karo
        run: docker build -t nitin-website ./my-first-docker

      - name: Docker images dekho
        run: docker images