name: Docker Build Action

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout karo
        uses: actions/checkout@v4

      - name: Docker Hub login karo
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build karo
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nitin-website .

      - name: Docker Hub pe push karo
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nitin-website