name: Mera Pehla Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello print karo
        run: echo "Hello Nitin! Action chal gaya!"

      - name: Date print karo
        run: date